import json
import time
import uuid

class ReportService:
    @staticmethod
    def generate_stix_bundle(scan_data):
        """
        Converts a ThreatLense scan result into a standard STIX 2.1 Bundle.
        """
        bundle_id = f"bundle--{uuid.uuid4()}"
        indicator_id = f"indicator--{uuid.uuid4()}"
        
        # Indicator Object for the URL
        indicator = {
            "type": "indicator",
            "spec_version": "2.1",
            "id": indicator_id,
            "created": time.strftime("%Y-%m-%dT%H:%M:%S.000Z"),
            "modified": time.strftime("%Y-%m-%dT%H:%M:%S.000Z"),
            "name": "Malicious URL Indicator",
            "description": "Indicator generated by ThreatLense ML Engine",
            "indicator_types": ["malicious-activity"],
            "pattern": f"[url:value = '{scan_data.get('url')}']",
            "pattern_type": "stix",
            "valid_from": time.strftime("%Y-%m-%dT%H:%M:%S.000Z")
        }
        
        # If OSINT found an IP
        ip_indicators = []
        osint_ip = scan_data.get("osint", {}).get("ip")
        if osint_ip:
            ip_id = f"indicator--{uuid.uuid4()}"
            ip_indicators.append({
                "type": "indicator",
                "spec_version": "2.1",
                "id": ip_id,
                "created": time.strftime("%Y-%m-%dT%H:%M:%S.000Z"),
                "modified": time.strftime("%Y-%m-%dT%H:%M:%S.000Z"),
                "name": "Associated IP Address",
                "indicator_types": ["malicious-activity"],
                "pattern": f"[ipv4-addr:value = '{osint_ip}']",
                "pattern_type": "stix",
                "valid_from": time.strftime("%Y-%m-%dT%H:%M:%S.000Z")
            })

        bundle = {
            "type": "bundle",
            "id": bundle_id,
            "objects": [indicator] + ip_indicators
        }
        
        return bundle
